[tool.poetry]
name = "david-xie123githubio"
version = "0.1.0"
description = ""
authors = ["DavidXie123 <<>>"]

[tool.poetry.dependencies]
python = "^2.7"
wheel = "^0.37.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
