name = "david-xie123githubio"
version = "0.1.0"
description = ""
authors = ["DavidXie123 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
wheel = "^0.37.1"
pip = "^22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
