[tool.poetry]
name = "David-Xie123githubio"
version = "0.1.0"
description = ""
authors = ["David-Xie123 <<>>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
poetry = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
